[package]
name = "recurring-dates-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.0"
chrono = "0.4.31"
rstest = "0.18.2"
